---
kind: "operation"
client: "rug-cli 0.17.1"
editor:
  name: "atomist-rugs.travis-editors.EnableTravisForRugArchiveDSL"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.4.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "ffa56d6"
  parameters:
    - "repo_slug": "atomist-rugs/rug-archive"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.18.1"
generator:
  name: "NewRugArchiveProject"
  group: "atomist-rugs"
  artifact: "rug-archive"
  version: "0.1.0"
  origin:
    repo: "atomist-rugs/rug-archive.git"
    branch: "f9a66acb09455472619aa92d805965960c25a6fa"
    sha: "f9a66ac"
  parameters:
    - "group_id": "org.spacecorpshandbook"
    - "version": "0.1.0"
    - "description": "Rug generator to create basic Space Corps Handbook Micorservices project structure"
    - "project_name": "schb-microservice"

